# Test your FastAPI endpoints
PUT http://localhost:8088/resource
Content-Type: application/json
{
  "resources": ["calculator", "weather", "notes"],
  "id": "user-123"
}
###
GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
